spring.application.name=protube-back
server.port=8080
spring.thymeleaf.prefix=classpath:/static/

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

spring.profiles.active=@spring.profiles.active@

# Database profile selection
# To switch to PostgreSQL, change 'h2' to 'postgres' in the lines below
spring.profiles.group.dev=h2
spring.profiles.group.prod=h2

# Path to the directory containing the videos (relative to the backend directory)

pro_tube.store.dir=videos/

spring.security.oauth2.client.registration.google.client-id=${ENV_PROTUBE_GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${ENV_PROTUBE_GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
spring.security.oauth2.client.provider.google.user-name-attribute=sub
spring.security.oauth2.client.provider.google.issuer-uri=https://accounts.google.com

spring.mvc.static-path-pattern=/media/**
logging.level.org.springframework.web=DEBUG

app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration=86400000
app.jwt.token-prefix=Bearer

#---
spring.config.activate.on-profile=dev
pro_tube.load_initial_data=true

#---
spring.config.activate.on-profile=prod
pro_tube.load_initial_data=false