spring.datasource.url=jdbc:postgresql://localhost:5432/${ENV_PROTUBE_DB}
spring.datasource.username=${ENV_PROTUBE_DB_USER}
spring.datasource.password=${ENV_PROTUBE_DB_PWD}
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
